Train:
  batch_size: 16
  lr: 0.0034
  betas: [0.9, 0.999]
  weight_decay: 0.01
  epochs: 5
  gamma: 0.5

network:
  model: MFNet
  load_checkpoint: False
  checkpoint_model_path: blah
  checkpoint_optimizer_path: blah
  start_epoch: 0 

data:
  train_data_dir: data/datasets/DNS_subset_10/train/noisy
  train_label_dir: data/datasets/DNS_subset_10/train/clean
  val_data_dir: data/datasets/DNS_subset_10/val/noisy
  val_label_dir: data/datasets/DNS_subset_10/val/clean
  save_every: 900
  save_dir: models/baseline
  save_best: True