Train:
  batch_size: 16
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.01
  epochs: 5
  gamma: 0.5
  steps: [10, 15, 20]
  

network:
  model: MFNet

data:
  train_data_dir: data/datasets/DNS_subset_10/train/noisy
  train_label_dir: data/datasets/DNS_subset_10/train/clean
  val_data_dir: data/datasets/DNS_subset_10/val/noisy
  val_label_dir: data/datasets/DNS_subset_10/val/clean
  save_best: True